/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2edd.folder;
import com.mycompany.proyecto2edd.ABEXP;
import com.mycompany.proyecto2edd.Interfaz;
import com.mycompany.proyecto2edd.NodoArbolBinario;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author andre
 */
public class ArbolGrafico extends javax.swing.JFrame {
        public static NodoArbolBinario v1 ;
//        ABEXP arbol = new ABEXP("(3+4*5)/(4+2)");

    /**
     * Creates new form ArbolGrafico
     * @param v1
     */
   public ArbolGrafico(NodoArbolBinario x) {
        v1 = x;
        
        initComponents();
    }
    
    public int dibujar(Graphics g, NodoArbolBinario x, int x0, int x1, int y){
        int m = (x0 + x1)/2;
        g.setColor(Color.orange);
        g.fillOval(m, y, 50, 40);
        g.setColor(Color.lightGray);
        g.setFont(new Font("Calibri", Font.BOLD, 22));
        String t = String.valueOf(x.dato);
        g.drawString(t, m+20, y+30);
        if(x.hijoDer != null){
            int x2 = dibujar(g, x.hijoDer, x0, m, y+50);
            g.drawLine(m+25, y+40, x2+25, y+50);
        }
        if(x.hijoIzq != null){
            int x2 = dibujar(g, x.hijoIzq, m, x1, y+50);
            g.drawLine(m+25, y+40, x2+25, y+50);
        }
        return m;
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        dibujar(g, v1, 0, this.getWidth()-25, 100 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolGrafico(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}


